sudo: required
services:
  - docker

before_install:
  #-t <docker username>/<github repo>  (the good naming convention, not compulsory)
  - docker build -t gabrielchong1994/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true gabrielchong1994/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-650645010175"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"