version: '3'
services:
  web:
    build:
      #specify where we want to files and folders for this image to pull from
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
     - /app/node_modules
     - .:/app
  #for testing
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]